### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by walterbender**
Fixed a typo/syntax error preventing the game from launching. More work is needed to resize for non-XO displays.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Looks like my review of https://github.com/sugarlabs/deducto/commit/656c9c8c1c4ad07b15831cdc2248e1a538b3d96d in https://github.com/sugarlabs/deducto/pull/11 wasn't so great.

Given that prior commit, isn't a `.format` required too?  @chimosky?

**Comment by chimosky** [comment]
> Thanks. Looks like my review of [656c9c8](https://github.com/sugarlabs/deducto/commit/656c9c8c1c4ad07b15831cdc2248e1a538b3d96d) in #11 wasn't so great.
> 

To be fair, I'd tested it in a REPL and it'd worked so it's basically my fault.
> Given that prior commit, isn't a `.format` required too? @chimosky?

Yeah it's required, I used f strings instead.

**Comment by quozl** [comment]
Thanks.  I don't understand why the ☒ and ☑ characters aren't in the message anyway.  What purpose is served by having them in global variables?

**Comment by chimosky** [comment]
Agreed, I can't even remember why I did that.

**Comment by quozl** [comment]
Thanks.  I see ffd1a7b.  So why not;

```python
self.status.set_label(_('Explore patterns with the ☑ and ☒ buttons.'))
```

Looking further back, as a result of [changing](https://github.com/sugarlabs/deducto/commit/656c9c8c1c4ad07b15831cdc2248e1a538b3d96d) what [the string was](https://github.com/sugarlabs/deducto/blame/656c9c8c1c4ad07b15831cdc2248e1a538b3d96d/po/Deducto.pot#L101) all the translations thereof are now missing.  They [no longer match](https://github.com/sugarlabs/deducto/blob/master/po/fr.po#L102) the code.  I suggest putting it back the way it was and ignoring the warning, or applying the same change to all the translations.  This brings up the problem of translate.sugarlabs.org again.

**Comment by chimosky** [comment]
I've applied same changes to all translations.

> This brings up the problem of translate.sugarlabs.org again.

Yes it does, sometime ago you mentioned something about uploading the activity po file to translate.sugarlabs.org. I don't know how translate.sugarlabs.org gets updated and I can't find the source code to take a look.

**Comment by quozl** [comment]
How it used to work;

* the translation tool is called Pootle, and is a Django web server app, hosted on translate.sugarlabs.org,
* it would fetch updated `po/*.pot` files from a list of repositories (many have since moved, and the fetch may not even be working right now),
* it would tell translators what needs doing and accept their work (this still happens),
* it would make commits and push to repositories the `po/*.po` files (this broke some time ago and, as you know, we download the changes using a hack of a script),

Here's some of the links I've got;

* [most up to date translate.sugarlabs.org technical documentation](http://wiki.sugarlabs.org/go/Service/translate),
* [listing of source repositories](https://wiki.sugarlabs.org/go/Translation_Team/Pootle_Projects/Repositories),
* [Sugar Labs translation-team issue repository](https://github.com/sugarlabs-infra/translation-team),
* [Translation Community Manager](https://wiki.sugarlabs.org/go/Translation-Community_Manager) (was a paid role, but no idea when it was last paid, contact @leonardcj),
* [Mailing LIst](http://lists.laptop.org/listinfo/localization), see the archives,
* [Maintenance Scripts](http://git.sugarlabs.org/projects/pootle-helpers),

Hope that helps.

**Pull request merged**
